# Site settings
title:  赵小闯
SEOTitle: 赵小闯的第一次尝试 | Zhaoxiaochuang Blog
header-img: img/home-bg.jpg
email: 1289248151
description: "这是赵小闯的博客"
keyword: ""
#url: "https://zhaoxiaochuang.github"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

repository: zhaoxiaochuang.github.io

# SNS settings
RSS: false
weibo_username:     13397221160
zhihu_username:     zhaoxiaochuang
github_username:    zhaoxiaochuang
twitter_username:   zhaoxiaochuang

# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
# disqus_username: zhaoxiaochuang.github.io





# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain:



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "The quieter you become, the more you hear"
sidebar-avatar: /img/138-140R6101917.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends:
  [
  {
        title: "zhaoxiaochuang",
        href: "https://user.qzone.qq.com/1289248151/infocenter"
    },
  {
        title: "Dandy Weng",
        href: "https://www.dandyweng.com/"
    }
]
